### ISSUE TITLE
Problems of building phasicFlow

### ISSUE THREAD

**Issue by Kyle-RuidongLI** [PhasicFlow/phasicFlow#129]
I have built the phasicFlow but with errors like this:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/globals/pFlowMacros.hpp:52:29: error: ‘__host__’ does not name a type
   52 |     #define FUNCTION_H      __host__
      |                             ^~~~~~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:216:17: note: in expansion of macro ‘FUNCTION_H’
  216 |                 FUNCTION_H
      |                 ^~~~~~~~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/globals/pFlowMacros.hpp:45:39: error: ‘__host__’ does not name a type
   45 |     #define INLINE_FUNCTION_HD inline __host__ __device__
      |                                       ^~~~~~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:231:17: note: in expansion of macro ‘INLINE_FUNCTION_HD’
  231 |                 INLINE_FUNCTION_HD
      |                 ^~~~~~~~~~~~~~~~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp: In static member function ‘static bool pFlow::symArray<T, MemorySpace>::getN(pFlow::uint32, pFlow::uint32&)’:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:240:44: error: no matching function for call to ‘sqrt(double)’
  240 |                         real nr = 0.5*(sqrt(8.0*nElem+1)-1);
      |                                        ~~~~^~~~~~~~~~~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:379,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/VectorMath.hpp:90:9: note: candidate: ‘template<class T, class Allocator> pFlow::Vector<T, Allocator> pFlow::sqrt(const pFlow::Vector<T, Allocator>&)’
   90 | VecFunc(sqrt);
      |         ^~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/VectorMath.hpp:26:29: note: in definition of macro ‘VecFunc’
   26 | inline Vector<T, Allocator> fnName(const Vector<T,Allocator>& v)        \
      |                             ^~~~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/VectorMath.hpp:90:9: note:   template argument deduction/substitution failed:
   90 | VecFunc(sqrt);
      |         ^~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/VectorMath.hpp:26:29: note: in definition of macro ‘VecFunc’
   26 | inline Vector<T, Allocator> fnName(const Vector<T,Allocator>& v)        \
      |                             ^~~~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:240:44: note:   mismatched types ‘const pFlow::Vector<T, Allocator>’ and ‘double’
  240 |                         real nr = 0.5*(sqrt(8.0*nElem+1)-1);
      |                                        ~~~~^~~~~~~~~~~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:379,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/VectorMath.hpp:90:9: note: candidate: ‘template<class T, class Allocator, class indexFunc> pFlow::Vector<T, Allocator> pFlow::sqrt(const pFlow::Vector<T, Allocator>&, indexFunc)’
   90 | VecFunc(sqrt);
      |         ^~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/VectorMath.hpp:36:29: note: in definition of macro ‘VecFunc’
   36 | inline Vector<T, Allocator> fnName(const Vector<T, Allocator>& v, indexFunc iFn)        \
      |                             ^~~~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/VectorMath.hpp:90:9: note:   template argument deduction/substitution failed:
   90 | VecFunc(sqrt);
      |         ^~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/VectorMath.hpp:36:29: note: in definition of macro ‘VecFunc’
   36 | inline Vector<T, Allocator> fnName(const Vector<T, Allocator>& v, indexFunc iFn)        \
      |                             ^~~~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:240:44: note:   mismatched types ‘const pFlow::Vector<T, Allocator>’ and ‘double’
  240 |                         real nr = 0.5*(sqrt(8.0*nElem+1)-1);
      |                                        ~~~~^~~~~~~~~~~~~
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:242:37: error: invalid initialization of reference of type ‘const word&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘pFlow::real’ {aka ‘double’}
  242 |                         if( equal(nr-static_cast<real>(n) , 0.0) ) return true;
      |                                   ~~^~~~~~~~~~~~~~~~~~~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/types/basicTypes/bTypes.hpp:26,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/types/types.hpp:24,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:26,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/types/basicTypes/bTypesFunctions.hpp:264:19: note: in passing argument 1 of ‘bool pFlow::equal(const word&, const word&)’
  264 | equal(const word& s1, const word& s2)
      |       ~~~~~~~~~~~~^~
make[2]: *** [src/phasicFlow/CMakeFiles/phasicFlow.dir/build.make:398: src/phasicFlow/CMakeFiles/phasicFlow.dir/streams/dataIO/dataIORegulars.cpp.o] Error 1
make[2]: *** [src/phasicFlow/CMakeFiles/phasicFlow.dir/build.make:650: src/phasicFlow/CMakeFiles/phasicFlow.dir/commandLine/commandLine.cpp.o] Error 1
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.hpp:137,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/stdVectorHelper.hpp:31,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:36,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.cpp: In instantiation of ‘bool pFlow::writeDataASCII(pFlow::iOstream&, pFlow::span<T>) [with T = std::__cxx11::basic_string<char>]’:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.cpp:235:24:   required from here
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.cpp:59:19: error: ‘class pFlow::span<std::__cxx11::basic_string<char> >’ has no member named ‘size’; did you mean ‘pFlow::uint32 pFlow::span<std::__cxx11::basic_string<char> >::size_’? (not accessible from this context)
   59 |         os<< data.size()<<endl;
      |              ~~~~~^~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:32,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/span/span.hpp:54:17: note: declared protected here
   54 |     uint32      size_   = 0;
      |                 ^~~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.hpp:137,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/stdVectorHelper.hpp:31,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:36,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.cpp:61:17: error: ‘class pFlow::span<std::__cxx11::basic_string<char> >’ has no member named ‘size’; did you mean ‘pFlow::uint32 pFlow::span<std::__cxx11::basic_string<char> >::size_’? (not accessible from this context)
   61 |         if(data.size()>0)
      |            ~~~~~^~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:32,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/span/span.hpp:54:17: note: declared protected here
   54 |     uint32      size_   = 0;
      |                 ^~~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.hpp:137,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/stdVectorHelper.hpp:31,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:36,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.cpp:63:40: error: ‘class pFlow::span<std::__cxx11::basic_string<char> >’ has no member named ‘size’; did you mean ‘pFlow::uint32 pFlow::span<std::__cxx11::basic_string<char> >::size_’? (not accessible from this context)
   63 |                 for(uint32 i=0; i<data.size()-1; i++)
      |                                   ~~~~~^~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:32,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/span/span.hpp:54:17: note: declared protected here
   54 |     uint32      size_   = 0;
      |                 ^~~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.hpp:137,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/stdVectorHelper.hpp:31,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:36,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.cpp:65:35: error: no match for ‘operator[]’ (operand types are ‘pFlow::span<std::__cxx11::basic_string<char> >’ and ‘pFlow::uint32’ {aka ‘unsigned int’})
   65 |                         os << data[i]<<token::NL;
      |                               ~~~~^
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/streams/dataIO/dataIO.cpp:67:33: error: ‘class pFlow::span<std::__cxx11::basic_string<char> >’ has no member named ‘size’; did you mean ‘pFlow::uint32 pFlow::span<std::__cxx11::basic_string<char> >::size_’? (not accessible from this context)
   67 |                 os << data[data.size()-1] << token::END_LIST;
      |                            ~~~~~^~~~
In file included from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/Vector/Vector.hpp:32,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrayHD.hpp:28,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.hpp:21,
                 from /home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/symArrayHD/symArrays.cpp:21:
/home/kyle/PhasicFlow/phasicFlow-v-1.0/src/phasicFlow/containers/span/span.hpp:54:17: note: declared protected here
   54 |     uint32      size_   = 0;
      |                 ^~~~~
make[2]: *** [src/phasicFlow/CMakeFiles/phasicFlow.dir/build.make:790: src/phasicFlow/CMakeFiles/phasicFlow.dir/containers/symArrayHD/symArrays.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1505: src/phasicFlow/CMakeFiles/phasicFlow.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

Can someone help me with this error? Many thanks.

**Comment by Kyle-RuidongLI** [comment]
I have successfully built one but got this :
Initializing host/device execution spaces . . . 
  Host execution space is Serial
  Device execution space is Cuda

Creating Control repository . . .
  libs are ()
Positioning points . . . 


>>> Fatal error in phasicFlow
Error occured in source file /home/kyle/PhasicFlow/phasicFlow/utilities/particlesPhasicFlow/positionParticles/positionParticles.cpp at line 145
Ctor Selector positionOrdered dose not exist. 
Avaiable ones are: 

empty
ordered
random

>>> phasicFlow is exiting . . .

**Comment by PhasicFlow** [comment]
Dear Kyle, 

The version that you have installed is the development version of phasicFlow. You may want to install the release-v-0.1 on your computer to work with a stable version (see https://github.com/PhasicFlow/phasicFlow/wiki/How-to-Build-PhasicFlow). In v-.01, all the tutorials are consistent. 
In the development version (v-1.0), we have not updated the tutorials according to the changes in the new version. You may want to have a look at this tutorial to see how you need to setup simulations in the new version:
https://github.com/PhasicFlow/phasicFlow/blob/main/tutorials/sphereGranFlow/binarySystemOfParticles
https://github.com/PhasicFlow/phasicFlow/tree/main/tutorials/sphereGranFlow/layeredSiloFilling 

Bests

**Comment by Kyle-RuidongLI** [comment]
Thank you, that solved my problem. Many thanks.
